// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx-kUdwT5eGIpuVJfkGWqRwCWhKXArnFI',
    appId: '1:631643443788:web:3b4f6644ece4b2d43adae9',
    messagingSenderId: '631643443788',
    projectId: 'raionkel6-b9044',
    authDomain: 'raionkel6-b9044.firebaseapp.com',
    storageBucket: 'raionkel6-b9044.firebasestorage.app',
    measurementId: 'G-D2Q9NB2V27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRww0Cwryl86CrT2VpLl4jXl5L6gLLN5o',
    appId: '1:631643443788:android:8a3d1d1325ee44613adae9',
    messagingSenderId: '631643443788',
    projectId: 'raionkel6-b9044',
    storageBucket: 'raionkel6-b9044.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPjBlVSbFiYu3foDalDVGYIiwT_Xw3lr4',
    appId: '1:631643443788:ios:5ba8d90626c4e9b23adae9',
    messagingSenderId: '631643443788',
    projectId: 'raionkel6-b9044',
    storageBucket: 'raionkel6-b9044.firebasestorage.app',
    iosBundleId: 'com.example.bersihin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPjBlVSbFiYu3foDalDVGYIiwT_Xw3lr4',
    appId: '1:631643443788:ios:5ba8d90626c4e9b23adae9',
    messagingSenderId: '631643443788',
    projectId: 'raionkel6-b9044',
    storageBucket: 'raionkel6-b9044.firebasestorage.app',
    iosBundleId: 'com.example.bersihin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx-kUdwT5eGIpuVJfkGWqRwCWhKXArnFI',
    appId: '1:631643443788:web:88092237582cd6c13adae9',
    messagingSenderId: '631643443788',
    projectId: 'raionkel6-b9044',
    authDomain: 'raionkel6-b9044.firebaseapp.com',
    storageBucket: 'raionkel6-b9044.firebasestorage.app',
    measurementId: 'G-6RNRBRPPCG',
  );
}
